### ISSUE TITLE
Fails to install from LuaRocks

### ISSUE THREAD

**Issue by jirutka** [spacewander/luabenchmark#1]
```
luarocks install luabenchmark 0.9.0-1
Installing https://luarocks.org/luabenchmark-0.9.0-1.src.rock

Error: File not found: luabenchmark-0.9.0-1.rockspec
```

The problem is that `luabenchmark-0.9.0-1.src.rock` file on LuaRocks does not contain `luabenchmark-0.9.0-1.rockspec`.

**Comment by spacewander** [comment]
Just release a new version with your contribution, called `0.10.0-1`. The installation should be not broken anymore.

**Comment by jirutka** [comment]
Thanks, now it works!
